sonar.projectKey=Amehran_field-report-ai
sonar.organization=amehran
sonar.projectName=field-report-ai
sonar.sources=app/src/main/java,backend/src
sonar.tests=app/src/test/java,backend/src/__tests__
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
# Encoding of the source code
sonar.sourceEncoding=UTF-8
