sonar.projectKey=Amehran_field-report-ai
sonar.organization=amehran
sonar.projectName=field-report-ai
sonar.sources=app/src/main/java,backend/src
# sonar.tests=app/src/test/java,app/src/androidTest/java

# Encoding of the source code
sonar.sourceEncoding=UTF-8
